CREATE TABLE `payments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`invoiceId` int NOT NULL,
	`stripePaymentIntentId` varchar(255) NOT NULL,
	`stripeCustomerId` varchar(255),
	`amount` decimal(10,2) NOT NULL,
	`currency` varchar(3) NOT NULL DEFAULT 'USD',
	`status` enum('pending','succeeded','failed','cancelled','refunded') NOT NULL DEFAULT 'pending',
	`paymentMethod` varchar(50),
	`lastFourDigits` varchar(4),
	`cardBrand` varchar(50),
	`description` text,
	`metadata` text,
	`failureReason` text,
	`refundedAmount` decimal(10,2) NOT NULL DEFAULT '0',
	`refundReason` text,
	`receiptUrl` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `payments_id` PRIMARY KEY(`id`),
	CONSTRAINT `payments_stripePaymentIntentId_unique` UNIQUE(`stripePaymentIntentId`)
);
--> statement-breakpoint
CREATE TABLE `roofMeasurements` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`projectId` int NOT NULL,
	`damageId` int,
	`estimateId` int,
	`latitude` decimal(10,8) NOT NULL,
	`longitude` decimal(11,8) NOT NULL,
	`roofAreaSqFt` decimal(10,2),
	`roofAreaSqMeters` decimal(10,2),
	`perimeterFt` decimal(10,2),
	`estimatedPitch` varchar(20),
	`boundaryPolygon` text,
	`zoomLevel` int NOT NULL DEFAULT 18,
	`imageUrl` text,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `roofMeasurements_id` PRIMARY KEY(`id`)
);
