import { useMemo, useState } from "react";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { AlertTriangle, Banknote, Building2, CalendarDays, CheckCircle2, ClipboardList, ReceiptText, Users, Wrench } from "lucide-react";
import { WORK_ORDER_STATUS_LABELS, type WorkOrderStatus } from "@shared/subcontractor";
import { getSubcontractorDashboardErrorState } from "@/lib/subcontractorDashboardState";

function toDateInput(date: Date) {
  return date.toISOString().slice(0, 10);
}

function setRange(days: number) {
  const end = new Date();
  const start = new Date();
  start.setDate(start.getDate() - days + 1);
  return { start: toDateInput(start), end: toDateInput(end) };
}

function Metric({ label, value, detail, icon: Icon, tone = "primary" }: { label: string; value: string | number; detail: string; icon: typeof ClipboardList; tone?: "primary" | "warning" | "danger" | "success" }) {
  const toneClasses = { primary: "text-primary bg-primary/10", warning: "text-amber-300 bg-amber-400/10", danger: "text-rose-300 bg-rose-400/10", success: "text-emerald-300 bg-emerald-400/10" };
  return <Card className="border-border/60 bg-card/60"><CardContent className="flex items-start justify-between gap-4 p-5"><div><p className="text-sm text-foreground/60">{label}</p><p className="mt-2 text-2xl font-bold tracking-tight">{value}</p><p className="mt-1 text-xs text-foreground/45">{detail}</p></div><div className={`rounded-lg p-2.5 ${toneClasses[tone]}`}><Icon className="h-5 w-5" /></div></CardContent></Card>;
}

export default function SubcontractorDashboard() {
  const initialRange = useMemo(() => setRange(30), []);
  const [range, setRangeState] = useState(initialRange);
  const startDate = new Date(`${range.start}T00:00:00`);
  const endDate = new Date(`${range.end}T23:59:59`);
  const { data, isLoading, isError, error, refetch } = trpc.subcontractorDashboard.get.useQuery({ startDate, endDate }, { enabled: !!range.start && !!range.end && endDate >= startDate, retry: false });
  const applyRange = (days: number) => setRangeState(setRange(days));

  if (isLoading) return <div className="py-20 text-center text-foreground/60">Loading subcontractor operations...</div>;
  if (isError) {
    const errorState = getSubcontractorDashboardErrorState({ code: error.data?.code, message: error.message });
    return <div className="mx-auto max-w-xl py-20 text-center"><AlertTriangle className="mx-auto h-10 w-10 text-amber-300" /><h1 className="mt-4 text-xl font-bold">{errorState.title}</h1><p className="mt-2 text-sm text-foreground/60">{errorState.message}</p><Button className="mt-5" variant="outline" onClick={() => refetch()}>Try again</Button></div>;
  }
  if (!data) return <div className="py-20 text-center text-foreground/60">Choose a valid reporting range to load the operations dashboard.</div>;

  return <div className="space-y-6">
    <section className="blueprint-section"><div className="blueprint-header flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><div className="flex items-center gap-2 text-primary"><Wrench className="h-5 w-5" /><span className="text-sm font-semibold uppercase tracking-wide">Subcontractor Operations</span></div><h1 className="mt-2 text-3xl font-bold">Operations Dashboard</h1><p className="mt-2 max-w-3xl text-sm text-foreground/65">Dispatch, exceptions, production, company performance, invoicing readiness, and receivables for the subcontractor-first workflow.</p></div><div className="flex flex-col gap-2 sm:flex-row sm:items-end"><div><label className="text-xs font-semibold uppercase tracking-wide text-foreground/55">Start</label><Input type="date" value={range.start} onChange={(event) => setRangeState((current) => ({ ...current, start: event.target.value }))} /></div><div><label className="text-xs font-semibold uppercase tracking-wide text-foreground/55">End</label><Input type="date" value={range.end} onChange={(event) => setRangeState((current) => ({ ...current, end: event.target.value }))} /></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => applyRange(7)}>7 days</Button><Button size="sm" variant="outline" onClick={() => applyRange(30)}>30 days</Button><Button size="sm" variant="outline" onClick={() => applyRange(90)}>90 days</Button></div></div></div></section>

    <section className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4"><Metric label="Active Work Orders" value={data.summary.activeWorkOrders} detail={`${data.summary.receivedWorkOrders} received in range`} icon={ClipboardList} /><Metric label="Completed Work" value={data.summary.completedWorkOrders} detail="Completed or past completion stage" icon={CheckCircle2} tone="success" /><Metric label="Ready to Invoice" value={data.summary.readyToInvoice} detail="Completed work awaiting billing" icon={ReceiptText} tone="warning" /><Metric label="Outstanding Receivables" value={`$${data.summary.outstandingReceivables.toFixed(2)}`} detail={`${data.summary.overdueInvoiceCount} overdue invoice${data.summary.overdueInvoiceCount === 1 ? "" : "s"}`} icon={Banknote} tone={data.summary.overdueInvoiceCount > 0 ? "danger" : "primary"} /></section>

    <section className="grid grid-cols-1 gap-6 xl:grid-cols-3"><Card className="border-border/60 bg-card/60 xl:col-span-2"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><AlertTriangle className="h-5 w-5 text-amber-300" /> Exceptions & Billing Queue</CardTitle></CardHeader><CardContent className="space-y-5"><div><div className="mb-3 flex items-center justify-between"><p className="text-sm font-semibold">Overdue Work Orders</p><Badge variant={data.exceptions.overdueWorkOrders.length > 0 ? "destructive" : "secondary"}>{data.exceptions.overdueWorkOrders.length}</Badge></div>{data.exceptions.overdueWorkOrders.length === 0 ? <p className="rounded-lg border border-dashed border-border p-4 text-sm text-foreground/60">No overdue active work orders.</p> : <div className="space-y-2">{data.exceptions.overdueWorkOrders.map((order) => <Link key={order.id} href={`/work-orders/${order.id}`} className="flex items-center justify-between gap-3 rounded-lg border border-rose-400/20 bg-rose-400/5 p-3 transition-colors hover:border-rose-400/50"><div><p className="text-sm font-semibold">{order.workOrderNumber} · {order.companyName}</p><p className="mt-1 text-xs text-foreground/60">Deadline {order.deadline ? new Date(order.deadline).toLocaleDateString("en-CA") : "not set"} · {WORK_ORDER_STATUS_LABELS[order.status as WorkOrderStatus]}</p></div><AlertTriangle className="h-4 w-4 shrink-0 text-rose-300" /></Link>)}</div>}</div><div className="border-t border-border/70 pt-5"><div className="mb-3 flex items-center justify-between"><p className="text-sm font-semibold">Ready to Invoice</p><Badge variant="outline">{data.exceptions.readyToInvoice.length}</Badge></div>{data.exceptions.readyToInvoice.length === 0 ? <p className="rounded-lg border border-dashed border-border p-4 text-sm text-foreground/60">No completed work orders are awaiting invoices.</p> : <div className="space-y-2">{data.exceptions.readyToInvoice.map((order) => <Link key={order.id} href={`/work-orders/${order.id}`} className="flex items-center justify-between gap-3 rounded-lg border border-amber-400/20 bg-amber-400/5 p-3 transition-colors hover:border-amber-400/50"><div><p className="text-sm font-semibold">{order.workOrderNumber} · {order.companyName}</p><p className="mt-1 text-xs text-foreground/60">{WORK_ORDER_STATUS_LABELS[order.status as WorkOrderStatus]}</p></div><ReceiptText className="h-4 w-4 shrink-0 text-amber-300" /></Link>)}</div>}</div></CardContent></Card>

      <Card className="border-border/60 bg-card/60"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><Users className="h-5 w-5 text-primary" /> Crew Production</CardTitle></CardHeader><CardContent>{data.crewProduction.length === 0 ? <p className="rounded-lg border border-dashed border-border p-5 text-sm text-foreground/60">Crew production appears after crews are scheduled against work orders.</p> : <div className="space-y-4">{data.crewProduction.map((entry) => <div key={entry.crew.id} className="rounded-lg border border-border/70 bg-background/30 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{entry.crew.name}</p><p className="mt-1 text-xs text-foreground/55">{entry.crew.crewLead || "No crew lead"}</p></div><Badge variant="outline">{entry.completedCount} complete</Badge></div><div className="mt-3 grid grid-cols-3 gap-2 text-xs"><div><p className="text-foreground/50">Scheduled</p><p className="mt-1 font-semibold">{entry.scheduledCount}</p></div><div><p className="text-foreground/50">Active</p><p className="mt-1 font-semibold">{entry.inProgressCount}</p></div><div><p className="text-foreground/50">Hours</p><p className="mt-1 font-semibold">{entry.labourHours.toFixed(1)}</p></div></div></div>)}</div>}</CardContent></Card></section>

    <section className="grid grid-cols-1 gap-6 xl:grid-cols-2"><Card className="border-border/60 bg-card/60"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><Building2 className="h-5 w-5 text-primary" /> Company Performance</CardTitle></CardHeader><CardContent>{data.companyPerformance.length === 0 ? <p className="rounded-lg border border-dashed border-border p-5 text-sm text-foreground/60">No partner work orders fall within the selected range.</p> : <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-sm"><thead className="border-b border-border/70 text-left text-xs uppercase tracking-wide text-foreground/55"><tr><th className="pb-3">Company</th><th className="pb-3 text-right">Orders</th><th className="pb-3 text-right">Complete</th><th className="pb-3 text-right">Rate</th><th className="pb-3 text-right">Labour Hrs</th></tr></thead><tbody>{data.companyPerformance.map((entry) => <tr key={entry.company.id} className="border-b border-border/50 last:border-0"><td className="py-3"><Link href={`/companies/${entry.company.id}`} className="font-medium hover:text-primary hover:underline">{entry.company.name}</Link></td><td className="py-3 text-right">{entry.workOrderCount}</td><td className="py-3 text-right">{entry.completedCount}</td><td className="py-3 text-right">{(entry.completionRate * 100).toFixed(0)}%</td><td className="py-3 text-right">{entry.labourHours.toFixed(1)}</td></tr>)}</tbody></table></div>}</CardContent></Card><Card className="border-border/60 bg-card/60"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><CalendarDays className="h-5 w-5 text-primary" /> Recent Work Orders</CardTitle></CardHeader><CardContent>{data.recentWorkOrders.length === 0 ? <p className="rounded-lg border border-dashed border-border p-5 text-sm text-foreground/60">No work orders have been created.</p> : <div className="space-y-3">{data.recentWorkOrders.map((order) => <Link key={order.id} href={`/work-orders/${order.id}`} className="flex items-center justify-between gap-3 rounded-lg border border-border/70 bg-background/30 p-3 transition-colors hover:border-primary/50"><div><p className="text-sm font-semibold">{order.workOrderNumber}</p><p className="mt-1 text-xs text-foreground/55">{order.companyName} · Updated {new Date(order.updatedAt).toLocaleDateString("en-CA")}</p></div><Badge variant="outline" className="capitalize">{WORK_ORDER_STATUS_LABELS[order.status as WorkOrderStatus]}</Badge></Link>)}</div>}</CardContent></Card></section>
  </div>;
}
