export const WORK_ORDER_STATUSES = [
  "new",
  "reviewed",
  "accepted",
  "scheduled",
  "assigned",
  "in_progress",
  "waiting",
  "completed",
  "ready_for_invoice",
  "invoiced",
  "partially_paid",
  "paid",
  "closed",
  "cancelled",
  "on_hold",
  "disputed",
  "callback_required",
] as const;

export type WorkOrderStatus = (typeof WORK_ORDER_STATUSES)[number];

export const WORK_ORDER_STATUS_LABELS: Record<WorkOrderStatus, string> = {
  new: "New",
  reviewed: "Reviewed",
  accepted: "Accepted",
  scheduled: "Scheduled",
  assigned: "Assigned",
  in_progress: "In Progress",
  waiting: "Waiting",
  completed: "Completed",
  ready_for_invoice: "Ready for Invoice",
  invoiced: "Invoiced",
  partially_paid: "Partially Paid",
  paid: "Paid",
  closed: "Closed",
  cancelled: "Cancelled",
  on_hold: "On Hold",
  disputed: "Disputed",
  callback_required: "Callback Required",
};

export const WORK_ORDER_NORMAL_TRANSITIONS: Record<WorkOrderStatus, WorkOrderStatus[]> = {
  new: ["reviewed", "accepted", "cancelled", "on_hold"],
  reviewed: ["accepted", "cancelled", "on_hold"],
  accepted: ["scheduled", "assigned", "cancelled", "on_hold", "disputed"],
  scheduled: ["assigned", "in_progress", "waiting", "cancelled", "on_hold", "disputed"],
  assigned: ["in_progress", "waiting", "cancelled", "on_hold", "disputed"],
  in_progress: ["waiting", "completed", "callback_required", "on_hold", "disputed"],
  waiting: ["in_progress", "completed", "cancelled", "on_hold", "disputed"],
  completed: ["ready_for_invoice", "callback_required", "disputed"],
  ready_for_invoice: ["invoiced", "disputed", "on_hold"],
  invoiced: ["partially_paid", "paid", "disputed"],
  partially_paid: ["paid", "disputed"],
  paid: ["closed", "callback_required", "disputed"],
  closed: ["callback_required"],
  cancelled: ["reviewed", "accepted"],
  on_hold: ["reviewed", "accepted", "scheduled", "assigned", "in_progress", "waiting", "completed", "ready_for_invoice", "invoiced", "partially_paid", "paid", "cancelled", "disputed", "callback_required"],
  disputed: ["reviewed", "accepted", "scheduled", "assigned", "in_progress", "waiting", "completed", "ready_for_invoice", "invoiced", "partially_paid", "paid", "cancelled", "on_hold", "callback_required"],
  callback_required: ["accepted", "scheduled", "assigned", "in_progress", "completed", "ready_for_invoice", "closed"],
};

export const WORK_ORDER_JOB_TYPES = [
  "tear_off",
  "shingle_installation",
  "flat_roofing",
  "repair",
  "flashing",
  "ventilation",
  "ice_water_protection",
  "underlayment",
  "metal_work",
  "skylight",
  "soffit_fascia",
  "eavestrough",
  "emergency_repair",
  "snow_work",
  "other",
] as const;

export type WorkOrderJobType = (typeof WORK_ORDER_JOB_TYPES)[number];

export const WORK_ORDER_JOB_TYPE_LABELS: Record<WorkOrderJobType, string> = {
  tear_off: "Tear-off",
  shingle_installation: "Shingle installation",
  flat_roofing: "Flat roofing",
  repair: "Repair",
  flashing: "Flashing",
  ventilation: "Ventilation",
  ice_water_protection: "Ice / water protection",
  underlayment: "Underlayment",
  metal_work: "Metal work",
  skylight: "Skylight",
  soffit_fascia: "Soffit / fascia",
  eavestrough: "Eavestrough",
  emergency_repair: "Emergency repair",
  snow_work: "Snow-related work",
  other: "Other",
};
